import { defineConfig } from "oxfmt";

export default defineConfig({
	useTabs: true,
	printWidth: 100,
	sortPackageJson: false,
	ignorePatterns: [
		"pnpm-lock.yaml",
		"dist/**",
		"dist-baseline/**",
		".velite/**",
		// registry.json is written by `pnpm registry`, and CI fails on any drift from what jsrepo emits
		"apps/docs/registry.json",
		// Regenerated by the comparison benchmark; formatting these would make every
		// re-run show up as a diff.
		"apps/comparison/RESULTS.md",
		"apps/comparison/bench/results/**",
	],
});
