import { defineConfig } from "oxfmt";

export default defineConfig({
	useTabs: true,
	printWidth: 100,
	sortPackageJson: false,
	ignorePatterns: [
		"pnpm-lock.yaml",
		"dist/**",
		"dist-baseline/**",
		".velite/**",
		// Regenerated by the comparison benchmark; formatting it would make every
		// re-run show up as a diff.
		"apps/comparison/RESULTS.md",
	],
});
