import { apiPartId, apiReference } from "./api-reference";

/** One heading in a page's table of contents, as generated by Velite's `s.toc()`. */
export type TocEntry = {
	title: string;
	url: string;
	items: TocEntry[];
};

type PageWithToc = { content: string; toc: TocEntry[] };

/**
 * A page's table of contents, with the parts of any `<div data-api>` API
 * reference added under the heading whose section contains the div. Those
 * headings render client-side (see the ApiReference component), so Velite's
 * markdown toc can't see them.
 */
export function pageToc(page: PageWithToc): TocEntry[] {
	const partsByHeading = new Map<string, TocEntry[]>();
	const orphans: TocEntry[] = [];

	const marker = /<h([2-6]) id="([^"]+)"|<div data-api="([^"]+)"/g;
	let headingId: string | undefined;
	for (const [, , id, api] of page.content.matchAll(marker)) {
		if (id != null) {
			headingId = id;
			continue;
		}
		const parts = apiReference[api ?? ""];
		if (parts == null) continue;
		const entries = parts.map((part) => ({
			title: part.name,
			url: `#${apiPartId(part.name)}`,
			items: [],
		}));
		if (headingId == null) orphans.push(...entries);
		else {
			const existing = partsByHeading.get(headingId) ?? [];
			partsByHeading.set(headingId, [...existing, ...entries]);
		}
	}

	if (partsByHeading.size === 0 && orphans.length === 0) return page.toc;

	const withParts = (entry: TocEntry): TocEntry => ({
		...entry,
		items: [...entry.items.map(withParts), ...(partsByHeading.get(entry.url.slice(1)) ?? [])],
	});

	return [...page.toc.map(withParts), ...orphans];
}
