/**
 * Turns the three result files into `apps/comparison/RESULTS.md`.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { APPS, forApp, RESULTS_DIR } from "./apps.ts";
import type { BenchReport } from "./bench.ts";
import type { DomCounts, DomReport } from "./dom-ops.ts";
import type { SizeReport } from "./size.ts";
import { STEPS } from "./steps.ts";

function readJson(name: string): unknown {
	return JSON.parse(readFileSync(resolve(RESULTS_DIR, name), "utf8"));
}

const kb = (bytes: number) => `${(bytes / 1024).toFixed(1)} kB`;
const mb = (bytes: number) => `${(bytes / 1024 / 1024).toFixed(1)} MB`;
const ratio = (value: number, best: number) => (best === 0 ? "—" : `${(value / best).toFixed(2)}×`);
const withRatio = (value: number, best: number, format: (value: number) => string) =>
	`${format(value)} (${ratio(value, best)})`;

function table(header: string[], rows: string[][]): string {
	return `${[
		`| ${header.join(" | ")} |`,
		`| ${header.map((_, i) => (i === 0 ? "---" : "---:")).join(" | ")} |`,
		...rows.map((row) => `| ${row.join(" | ")} |`),
	].join("\n")}\n`;
}

function lowest(values: number[]): number {
	const positive = values.filter((value) => value > 0);
	return positive.length === 0 ? 0 : Math.min(...positive);
}

function sizeSection(sizes: SizeReport): string {
	const appJs = APPS.map((app) => forApp(sizes, app.id).app.js.gzip);
	const rows = APPS.map((app) => {
		const { app: built, baseline } = forApp(sizes, app.id);
		return [
			app.label,
			kb(built.js.raw),
			kb(built.js.gzip),
			kb(built.js.brotli),
			kb(baseline.js.gzip),
			kb(built.js.gzip - baseline.js.gzip),
			ratio(built.js.gzip, lowest(appJs)),
		];
	});
	return table(
		["", "app JS", "gzip", "brotli", "hello world (gzip)", "app's own code (gzip)", "vs. best"],
		rows,
	);
}

function timingSection(bench: BenchReport): string {
	const rows = STEPS.map((step) => {
		const medians = APPS.map((app) => forApp(bench.apps, app.id).steps[step.label]?.median ?? 0);
		const fastest = lowest(medians);
		return [
			step.label,
			...medians.map((value) => withRatio(value, fastest, (ms) => ms.toFixed(0))),
		];
	});

	const mounted = APPS.map((app) => forApp(bench.apps, app.id).mounted.median);
	rows.push([
		"**time to mounted**",
		...mounted.map((value) => withRatio(value, lowest(mounted), (ms) => ms.toFixed(0))),
	]);

	const heap = APPS.map((app) => forApp(bench.apps, app.id).heap10k.median);
	rows.push([
		"**JS heap at 10k rows**",
		...heap.map((value) => withRatio(value, lowest(heap), mb)),
	]);

	return table(["median ms, lower is better", ...APPS.map((app) => app.label)], rows);
}

function domSection(dom: DomReport, field: keyof DomCounts): string {
	const rows = STEPS.map((step) => [
		step.label,
		...APPS.map((app) => String(forApp(dom, app.id).steps[step.label]?.[field] ?? 0)),
	]);
	return table([field, ...APPS.map((app) => app.label)], rows);
}

function main() {
	const sizes: SizeReport = [];
	const parsedSizes = readJson("sizes.json");
	if (Array.isArray(parsedSizes)) sizes.push(...parsedSizes);

	const parsedBench = readJson("bench.json");
	if (parsedBench === null || typeof parsedBench !== "object" || !("apps" in parsedBench)) {
		throw new Error("bench.json is not a report");
	}
	const bench: BenchReport = Object.assign(
		{ reps: 0, warmup: 0, browser: "unknown", apps: [] },
		parsedBench,
	);

	const dom: DomReport = [];
	const parsedDom = readJson("dom-ops.json");
	if (Array.isArray(parsedDom)) dom.push(...parsedDom);

	const markdown = [
		"<!-- Generated by `pnpm --filter @comparison/bench report`. Do not edit by hand. -->",
		"",
		"# Measured results",
		"",
		`Chromium ${bench.browser}. ${bench.reps} timed runs per app after ${bench.warmup} warmup`,
		"runs, each run in a fresh page. Every number below is a median.",
		"",
		"## What ships to the client",
		"",
		sizeSection(sizes),
		"The stylesheet is byte-for-byte identical in all three apps (3.2 kB, 1.2 kB gzipped)",
		"and is left out of the table.",
		"",
		"## How long an update takes to reach the screen",
		"",
		timingSection(bench),
		"## DOM nodes created",
		"",
		domSection(dom, "created"),
		"## DOM insertions and moves",
		"",
		domSection(dom, "inserted"),
		"## DOM removals",
		"",
		domSection(dom, "removed"),
		"## Attribute writes",
		"",
		domSection(dom, "attrWrites"),
		"## Text writes",
		"",
		domSection(dom, "textWrites"),
	].join("\n");

	const out = resolve(RESULTS_DIR, "../../RESULTS.md");
	writeFileSync(out, markdown);
	console.log(`wrote ${out}`);
}

main();
